account: main_account
as_of: "2025-01-18 09:25:00"

positions:
#金正股份
  sh600446:
    direction: LONG
    size: 3
    entry_price: 16.73
    stop_loss: 16.5
    take_profit: 17.2
#实益达
  sh002137:
    direction: LONG
    size: 25
    entry_price: 9.06
    stop_loss: 8.2
    take_profit: 9.8
#中油资本
  sh000617:
    direction: LONG
    size: 5
    entry_price: 10.16
    stop_loss: 9
    take_profit: 10.5
